# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: ELEC4630
description: A small blog about my journey through ELEC4630.
github_username: AndreasUtkilen

# Email and twitter are optional:
email:
twitter_username:

# Set this to true to get LaTeX math equation support
use_math:

animation:
  enabled: true # enables css animation of individual elements
  selector: "audio, blockquote, div.card, div.highlighter-rouge, div.news, div.repositories, div.row, div.social, div.tag-category-list, figure, h2, h3, ol, p, tr, ul, video"
  name: enter # name of your animation
  duration: 0.6s
  # `from` and `to` can be either a string or a hash. Here you can see an example of both usages
  from:
    opacity: 0
    transform: translateY(10px)
  to: "opacity:1;transform:none"
  delay: 100ms # delay before each consecutive animation starts
  # note that usually not more than 20 elements need to be animated, since they will be outside the screen
  max_elements: 20 # maximum number of elements to animate (set to -1 to animate all elements)
  verbose: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
